"""Morning report generator (workplan v6 Step 4).

Pulls live state from Supabase + the most recent run-stats artifact, writes
a Markdown summary to ``artifacts/overnight-report-<date>.md``.
"""

from __future__ import annotations

import json
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rich.console import Console

from ..db import REPO_ROOT, connect

console = Console()


@dataclass
class Counts:
    vcs_total: int = 0
    vcs_with_careers: int = 0
    jobs_total: int = 0
    jobs_active: int = 0
    jobs_inactive: int = 0
    by_source: dict[str, int] = field(default_factory=dict)
    by_category: dict[str, int] = field(default_factory=dict)
    by_company: list[tuple[str, int]] = field(default_factory=list)


def _scalar(value: Any) -> int:
    return int(value) if value is not None else 0


def _latest_run_stats(artifacts: Path) -> dict[str, Any] | None:
    candidates = sorted(artifacts.glob("run-stats-*.json"))
    if not candidates:
        return None
    raw: Any = json.loads(candidates[-1].read_text(encoding="utf-8"))
    return raw if isinstance(raw, dict) else None


def _query_counts() -> Counts:
    counts = Counts()
    with connect() as conn, conn.cursor() as cur:
        cur.execute("select count(*) from vcs;")
        row = cur.fetchone()
        counts.vcs_total = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from vcs where careers_url is not null and careers_url <> '';")
        row = cur.fetchone()
        counts.vcs_with_careers = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs;")
        row = cur.fetchone()
        counts.jobs_total = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs where is_active = true;")
        row = cur.fetchone()
        counts.jobs_active = _scalar(row[0]) if row else 0
        cur.execute("select count(*) from jobs where is_active = false;")
        row = cur.fetchone()
        counts.jobs_inactive = _scalar(row[0]) if row else 0
        cur.execute(
            "select ats_source, count(*) from jobs where is_active = true group by ats_source;"
        )
        counts.by_source = {str(s): int(c) for s, c in cur.fetchall()}
        cur.execute(
            "select role_category, count(*) from jobs where is_active = true group by role_category;"
        )
        counts.by_category = {
            (str(s) if s else "tier2_pending"): int(c) for s, c in cur.fetchall()
        }
        cur.execute(
            "select company_name, count(*) from jobs where is_active = true "
            "group by company_name order by 2 desc;"
        )
        counts.by_company = [(str(c), int(n)) for c, n in cur.fetchall()]
    return counts


def _list_invalid_quarantine(artifacts: Path) -> list[tuple[str, int]]:
    out: list[tuple[str, int]] = []
    for path in sorted(artifacts.glob("invalid_jobs_*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            count = len(data) if isinstance(data, list) else 0
        except (json.JSONDecodeError, OSError):
            count = -1
        out.append((path.name, count))
    return out


def main() -> int:
    artifacts = REPO_ROOT / "artifacts"
    counts = _query_counts()
    run = _latest_run_stats(artifacts)
    invalid = _list_invalid_quarantine(artifacts)
    today = time.strftime("%Y-%m-%d", time.gmtime())
    out_path = artifacts / f"overnight-report-{today.replace('-', '')}.md"

    lines: list[str] = []
    lines.append(f"# Career-Buddy overnight report — {today}\n")
    lines.append(
        "Layer-1 first-run synthesis. Generated by "
        "`career_buddy_scraper.cli.report`.\n\n"
    )

    lines.append("## Headline numbers\n")
    lines.append(f"- VCs in master list      : **{counts.vcs_total}**")
    lines.append(f"- VCs with `careers_url`  : **{counts.vcs_with_careers}**")
    lines.append(f"- Jobs total (all-time)   : **{counts.jobs_total}**")
    lines.append(f"- Jobs active             : **{counts.jobs_active}**")
    lines.append(f"- Jobs inactive           : **{counts.jobs_inactive}**\n")

    lines.append("## Active jobs by ATS source\n")
    for src, n in sorted(counts.by_source.items()):
        lines.append(f"- `{src}`: {n}")
    lines.append("")

    lines.append("## Active jobs by role-category (Tier-1 regex)\n")
    for cat, n in sorted(counts.by_category.items()):
        lines.append(f"- `{cat}`: {n}")
    lines.append("")

    lines.append("## Active jobs by company\n")
    for company, n in counts.by_company:
        lines.append(f"- {company}: {n}")
    lines.append("")

    if run is not None:
        stats = run.get("stats", {})
        if isinstance(stats, dict):
            lines.append("## Most recent run stats\n")
            lines.append(f"- Started UTC      : {run.get('timestamp_utc')}")
            duration_s = stats.get("duration_s")
            duration_str = f"{duration_s:.1f}s" if isinstance(duration_s, (int, float)) else "n/a"
            lines.append(f"- Duration         : {duration_str}")
            lines.append(f"- VCs matched      : {stats.get('vcs_matched')}/{stats.get('vcs_total')}")
            lines.append(f"- VCs unmatched    : {stats.get('vcs_unmatched')}")
            lines.append(f"- Rows fetched     : {stats.get('rows_fetched')}")
            lines.append(f"- Rows valid       : {stats.get('rows_valid')}")
            lines.append(f"- Rows invalid     : {stats.get('rows_invalid')}")
            lines.append(f"- Inserted         : {stats.get('inserted')}")
            lines.append(f"- Updated          : {stats.get('updated')}")
            lines.append(f"- Marked stale     : {stats.get('affected_stale')}")
            lines.append("")
        limiter = run.get("limiter_metrics", {})
        if isinstance(limiter, dict):
            lines.append("## HTTP limiter metrics (most recent run)\n")
            lines.append(f"- Total requests   : {limiter.get('total_requests')}")
            lines.append(f"- Cache hits       : {limiter.get('cache_hits')}")
            lines.append(f"- Peak req/min     : {limiter.get('peak_per_minute')}")
            by_method = limiter.get("by_method", {})
            by_status = limiter.get("by_status", {})
            lines.append(f"- By method        : {dict(sorted(by_method.items())) if isinstance(by_method, dict) else 'n/a'}")
            lines.append(f"- By status        : {dict(sorted(by_status.items())) if isinstance(by_status, dict) else 'n/a'}")
            lines.append("")
        errors = run.get("errors", [])
        if isinstance(errors, list) and errors:
            lines.append("## Errors\n")
            for err in errors:
                lines.append(f"- {err}")
            lines.append("")

    if invalid:
        lines.append("## Invalid-jobs quarantine\n")
        for fname, n in invalid:
            lines.append(f"- `{fname}`: {n} rows")
        lines.append("")
    else:
        lines.append("## Invalid-jobs quarantine\n\nNo quarantine artifacts produced — every fetched row passed Pydantic validation.\n")

    lines.append("## Yield-gate analysis\n")
    active = counts.jobs_active
    lines.append(f"- Active jobs in DB: **{active}**")
    if active >= 30:
        lines.append("- Yield-gate: **MET** (≥ 30 active jobs).")
    else:
        lines.append(
            f"- Yield-gate: **shortfall** (target ≥ 30, observed {active})."
        )
        lines.append(
            "- Workplan v6 fallback path: shortfall is documented here "
            "AND `jobs_inserted_or_updated > 0` (the first run inserted 158 rows; "
            "141 were deactivated as Notion Labs / Notion Capital VC contamination)."
        )
    lines.append("")

    lines.append("## Findings\n")
    lines.append(
        "1. **Most VCs do not run public ATS boards for their internal roles.** Of 15 "
        "Tier-1 VCs seeded, only 7 had a discoverable ATS slug across Greenhouse, "
        "Lever, Ashby, Workable. Of those 7, 4 returned ≥ 1 active role. The "
        "remaining 8 (Project A, Speedinvest, HV-via-`hv`, Lakestar, Plural, "
        "Balderton, Creandum, Point Nine, Founders Fund) hire via personal networks "
        "or use ATSes outside our four-adapter coverage."
    )
    lines.append(
        "2. **Slug-name collision on Ashby `notion`.** The slug returns Notion Labs "
        "(productivity SaaS, 141 jobs) — not Notion Capital VC. 141 rows were "
        "deactivated and Notion Capital's `careers_url` reverted to `notion.vc/careers`. "
        "Future scrapes will skip it. The contaminated rows remain in the DB with "
        "`is_active = false` for audit."
    )
    lines.append(
        "3. **Cherry Ventures' `talent.cherry.vc/jobs` board is portfolio-company "
        "recruiting, not Cherry's own roles.** The 11 active rows under Cherry are "
        "actually positions at Cherry-portfolio startups (Founding Engineer, Customer "
        "Success Lead, FP&A, etc.). This is still useful for Career-Buddy users but "
        "should be modelled separately (a `posted_by_vc` column might fit)."
    )
    lines.append(
        "4. **Tier-1 regex coverage on the operator track is low.** 1/17 active rows "
        "(6%) matched the high-precision Tier-1 patterns. The other 16 are mostly "
        "engineering or VC-internal admin titles where Tier-2 LLM classification "
        "(deferred until an `ANTHROPIC_API_KEY` is provisioned) would help."
    )
    lines.append(
        "5. **HTML-discovery hop alone is insufficient for VC career pages.** All 15 "
        "primary VCs failed direct-detect AND HTML-discovery on their own homepages "
        "until we manually pinned 7 of them to verified ATS endpoints. A Phase A.1 "
        "OpenVC + EU-Startups CSV import is needed to hit the 200-job stretch goal "
        "in `scraper-plan.md`."
    )
    lines.append("")

    lines.append("## Recommended next actions\n")
    lines.append(
        "1. **Phase A.1 — OpenVC + EU-Startups CSV ingest.** Get an order-of-magnitude "
        "more VCs into `vcs`, dedupe against the Notion seed, expect ~1,500 rows. Even "
        "if only 5% have direct ATS slugs that's ~75 boards to scrape."
    )
    lines.append(
        "2. **Phase C — portfolio-company scrape.** Cherry's portfolio jobs (and similar "
        "talent boards from Speedinvest, Project A) are the real volume source. The "
        "`scraper-plan.md` Phase C pulls portfolio company lists per VC and runs the "
        "same 4 ATS adapters."
    )
    lines.append(
        "3. **Tier-2 LLM classifier.** Provision `ANTHROPIC_API_KEY`, build the cheap "
        "Claude-Haiku-4.5 classifier on (title + first 500 chars of description), "
        "back-fill `role_category` for the 16 currently-pending rows."
    )
    lines.append(
        "4. **Schema add: `posted_by_vc TEXT`** so portfolio-recruiting boards (Cherry's "
        "`talent.cherry.vc`, Speedinvest's similar talent-redirection page) can be "
        "stored without conflating the hiring company with the VC firm."
    )
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(f"[green]wrote {out_path}[/green]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
