/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as CvRouteImport } from './routes/cv'
import { Route as BuddyRouteImport } from './routes/buddy'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyRoute = BuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buddy': typeof BuddyRoute
  '/cv': typeof CvRoute
  '/design-preview': typeof DesignPreviewRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buddy': typeof BuddyRoute
  '/cv': typeof CvRoute
  '/design-preview': typeof DesignPreviewRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buddy': typeof BuddyRoute
  '/cv': typeof CvRoute
  '/design-preview': typeof DesignPreviewRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buddy' | '/cv' | '/design-preview' | '/jobs' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buddy' | '/cv' | '/design-preview' | '/jobs' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/buddy'
    | '/cv'
    | '/design-preview'
    | '/jobs'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuddyRoute: typeof BuddyRoute
  CvRoute: typeof CvRoute
  DesignPreviewRoute: typeof DesignPreviewRoute
  JobsRoute: typeof JobsRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy': {
      id: '/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof BuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuddyRoute: BuddyRoute,
  CvRoute: CvRoute,
  DesignPreviewRoute: DesignPreviewRoute,
  JobsRoute: JobsRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
